name: Dead Domains Threat

on:
  schedule:
    - cron: '20 */6 * * *'
  workflow_dispatch:
  
jobs:
  run-linter-threat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i -g @adguard/dead-domains-linter

      - name: Run DeadDomainsLinter
        run: |
          dead-domains-linter -i threat.txt --export=threat-DeadDomains.txt

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add .
          git commit -m "chore: updated threat-DeadDomains.txt results" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
