name: Dead Domains Gambling

on:
  schedule:
    - cron: '20 */6 * * *'
  workflow_dispatch:
  
jobs:
  run-linter-gambling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i -g @adguard/dead-domains-linter

      - name: Run DeadDomainsLinter
        run: |
          dead-domains-linter -i gambling.txt --export=gambling-DeadDomains.txt

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git stash
          git pull --rebase origin main
          git stash pop || echo "No local changes to apply"
          git add .
          git commit -m "chore: updated gambling-DeadDomains.txt results" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
