name: Dead Domains Linter

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
  
jobs:
  run-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Download Script
        run: |
          chmod +x download.sh
          ./download.sh

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i -g @adguard/dead-domains-linter

      - name: Run DeadDomainsLinter
        run: |
          dead-domains-linter -i hostsVN.txt --export=hostsVN-DeadDomains.txt
          dead-domains-linter -i adult.txt --export=adult-DeadDomains.txt
          dead-domains-linter -i gambling.txt --export=gambling-DeadDomains.txt
          dead-domains-linter -i threat.txt --export=threat-DeadDomains.txt

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: updated linter results"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
